import Link from 'next/link';

import { PublicPolicyLayout } from '@/components/legal/PublicPolicyLayout';

export const metadata = { title: 'Privacy Policy · Ops Solutions', description: 'How Ops Solutions handles customer account and HubSpot analytics data.' };

export default function PrivacyPage() {
  const sections = [
    { id: 'scope', title: 'Scope and roles', content: <><p>This policy covers the Ops Solutions website, customer application, HubSpot integration, reports, alerts and support operations. For CRM data synchronized from a customer HubSpot account, the customer remains the controller and Ops Solutions acts as a processor operating on documented customer instructions.</p><p>Account, billing, security and support information is processed to provide and protect the service.</p></> },
    { id: 'data', title: 'Information we process', content: <><ul><li>Account identity, workspace membership, role and authentication events.</li><li>HubSpot portal metadata, CRM properties, owners, pipelines, records and associations authorized by the connected OAuth scopes.</li><li>Dashboard configuration, semantic mappings, budget imports, saved views, exports, schedules and alert rules.</li><li>Operational diagnostics, audit events and privacy-reduced device or network signals used to secure accounts.</li><li>Support communications and service administration records.</li></ul><div className="legal-callout">Ops Solutions does not sell customer data and the production analytics release does not write changes back to customer HubSpot records.</div></> },
    { id: 'purpose', title: 'Why we process information', content: <ul><li>Authenticate users and enforce tenant isolation and role-based access.</li><li>Connect to HubSpot, synchronize authorized data and generate dashboards.</li><li>Provide exports, retention analysis, scheduled reports and operational alerts.</li><li>Prevent abuse, investigate security events, maintain backups and recover the service.</li><li>Meet legal obligations and respond to verified privacy requests.</li></ul> },
    { id: 'sharing', title: 'Service providers and transfers', content: <><p>We use infrastructure, database, email delivery and monitoring providers only as needed to operate the service. Access is limited by role and contractual or technical safeguards. Customer data is not disclosed to advertisers or data brokers.</p><p>Where information crosses borders, we apply appropriate contractual and security safeguards for the applicable relationship.</p></> },
    { id: 'retention', title: 'Retention and deletion', content: <><p>Customer CRM data is retained while a workspace is active and for a limited operational period after disconnection or termination, subject to backup rotation, legal obligations and an agreed customer contract. Expired exports and transient delivery artifacts are removed automatically.</p><p>Verified deletion requests can be initiated through the <Link href="/data-deletion">Data Deletion page</Link>.</p></> },
    { id: 'security', title: 'Security', content: <><p>OAuth credentials are encrypted at rest. Customer routes are authenticated and workspace scoped. PostgreSQL and Redis are not publicly exposed. Production changes pass automated validation, dependency checks, backup verification and rollback controls.</p><p>Read more in the <Link href="/security">Security Overview</Link>.</p></> },
    { id: 'rights', title: 'Your choices and rights', content: <><p>Depending on applicable law, individuals may request access, correction, deletion, restriction, portability or objection. CRM data requests should normally be directed to the organization controlling the connected HubSpot portal. Ops Solutions assists customers with verified requests.</p><p>For privacy questions, use the verified channels on the <Link href="/support">Support page</Link>.</p></> }
  ];
  return <PublicPolicyLayout eyebrow="Privacy" title="Privacy built around customer control." summary="This policy explains what Ops Solutions processes, why it is needed, how it is protected and how verified privacy requests are handled." sections={sections} />;
}
