import Link from 'next/link';

import { PublicPolicyLayout } from '@/components/legal/PublicPolicyLayout';

export const metadata = { title: 'Terms of Service · Ops Solutions', description: 'Terms governing access to Ops Solutions HubSpot analytics.' };

export default function TermsPage() {
  const sections = [
    { id: 'service', title: 'The service', content: <><p>Ops Solutions provides tenant-isolated HubSpot analytics, synchronized reporting, exports, retention intelligence, scheduled delivery and operational alerting. Features may vary by plan, connected scopes and customer configuration.</p><p>The customer is responsible for ensuring it has authority to connect a HubSpot portal and process the information made available to the service.</p></> },
    { id: 'accounts', title: 'Accounts and access', content: <ul><li>Users must provide accurate account information and keep credentials secure.</li><li>Workspace owners and administrators control invitations, roles, mappings, imports, schedules and alerts.</li><li>Customers must promptly revoke access for users who should no longer use the service.</li><li>Automated access, scraping, circumvention of limits or interference with service security is prohibited.</li></ul> },
    { id: 'data', title: 'Customer data', content: <><p>The customer retains ownership of customer data. The customer grants Ops Solutions the limited right to host, process, transform and display that data solely to provide, secure and support the service.</p><p>Ops Solutions does not acquire ownership of HubSpot records and does not sell customer data.</p></> },
    { id: 'plans', title: 'Plans, trials and payment', content: <><p>Trials and plan entitlements may be limited by users, synchronized records, exports, schedules, workspaces or other published limits. Managed deployments may follow a separate order form.</p><p>Until a live payment provider is enabled, plan changes are administrative and no payment card is charged. Once live billing is enabled, pricing, renewal and cancellation terms shown at checkout or in an order form apply.</p></> },
    { id: 'availability', title: 'Availability and changes', content: <><p>We work to provide a reliable service but do not guarantee uninterrupted availability. Maintenance, HubSpot API limits, provider outages, customer configuration and force majeure events may affect operation.</p><p>We may improve or replace features while preserving materially equivalent customer capabilities where reasonably possible.</p></> },
    { id: 'acceptable-use', title: 'Acceptable use', content: <ul><li>Do not use the service unlawfully or to violate privacy, employment, marketing or data-protection obligations.</li><li>Do not upload malicious code, attempt unauthorized access or probe another tenant.</li><li>Do not resell access except under an authorized partner or managed-service agreement.</li><li>Do not rely on dashboards as the sole basis for decisions requiring legal, financial or professional judgment.</li></ul> },
    { id: 'termination', title: 'Suspension and termination', content: <><p>Access may be suspended for material security risk, unlawful use, non-payment after live billing is enabled or a serious breach of these terms. Customers may cancel according to their plan or order form.</p><p>Following termination, data is handled under the <Link href="/privacy">Privacy Policy</Link> and verified deletion process.</p></> },
    { id: 'liability', title: 'Warranties and liability', content: <><p>The service is provided with reasonable care but analytics depend on source data quality, mappings and third-party availability. To the maximum extent permitted by law, implied warranties are excluded and indirect or consequential damages are limited.</p><p>Any negotiated order form or enterprise agreement controls where it conflicts with these public terms.</p></> },
    { id: 'contact', title: 'Contact and governing terms', content: <p>Questions, notices and support requests should be submitted through the <Link href="/support">Support page</Link>. The governing law and dispute venue may be specified in the applicable order form or customer agreement.</p> }
  ];
  return <PublicPolicyLayout eyebrow="Terms" title="Clear operating terms for a connected analytics service." summary="These terms set the baseline responsibilities for using Ops Solutions, connecting HubSpot data and managing a customer workspace." sections={sections} />;
}
